### ISSUE TITLE
How I can get output from sevenZip.callMain(["l", ''archive.zip"])

### ISSUE THREAD

**Issue by anzolo** [use-strict/7z-wasm#12]
Hello! I try to create some kind of archiver with web interface. I want to get contents of archive and show it at web page.  
Does your library allow you to get the entire output of the executed command? Or I need to monkey-patch console.log and get output of command from there? Thanx for answer!

**Comment by use-strict** [comment]
See https://github.com/use-strict/7z-wasm/blob/master/cli.js#L20 as example
