### ISSUE TITLE
How to decompress from memory ?

### ISSUE THREAD

**Issue by jespa007** [use-strict/7z-wasm#16]
Hi,
In the README.md shows an example to decompress from file. 

How can I decompress from memory (i.e from a blob or ByteArray) ?

Thanks,

**Comment by use-strict** [comment]
The first example in the README covers your exact case. Emscripten uses a memory file system as root, so all you have to do is "write" your `Uint8Array` to a virtual file and pass the file name as argument to 7-Zip. You can also pass the `canOwn` parameter to the `write` method to prevent it from copying the array and use it as a transferable object instead.

The real file system is only used if you mount it, like in the second example from the README.
