### ISSUE TITLE
npx 7z-wasm failed to parse url error

### ISSUE THREAD

**Issue by shubhendusaurabh** [use-strict/7z-wasm#18]
on running `npx 7z-wasm` on cli getting error

`TypeError: Failed to parse URL from <path>/node_modules/7z-wasm/7zz.wasm
    at Object.fetch (node:internal/deps/undici/undici:11457:11) {
  [cause]: TypeError [ERR_INVALID_URL]: Invalid URL`

i'm using node v18.16

**Comment by G1ya777** [comment]
i'm having the same!

**Comment by shubhendusaurabh** [comment]
this is due to new fetch api in node v18 and above.

cli works with v16.

other option is to `export NODE_OPTIONS='--no-experimental-fetch'`
