### ISSUE TITLE
Cant open password protected 7z files

### ISSUE THREAD

**Issue by adyster** [use-strict/7z-wasm#2]
Throws an error when trying to open password protected 7z files.

**Comment by use-strict** [comment]
What's the exact error you are seeing?

I tried to test it with a password-protected archive, and it seems to simply get stuck whenever input is needed from stdin. As a workaround I was able to extract such an archive by specifying the password via command argument (not recommended security-wise) and the -y flag to suppress any overwrite prompts.

E.g. `7z-wasm -p1234 -y x archive.7z`

**Comment by adyster** [comment]
Actually, never mind. I was still running the b2 version. Works with the newer update. :-)

**Comment by use-strict** [comment]
Fixed in v1.0.0-beta.4
