### ISSUE TITLE
put wasm to assets 

### ISSUE THREAD

**Issue by vinnitu** [use-strict/7z-wasm#20]
Hello. Glory to Ukraine!

I made vue app and add 7z-wasm to project;

In App.vue 

```js
import SevenZip from "7z-wasm";
const sevenZip = await SevenZip();
```

In browser console see
 
App.vue:46     GET http://localhost:5173/node_modules/.vite/deps/7zz.wasm 404 (Not Found)

how to configure path to 7zz.wasm if I placed it to assets dir?

**Comment by vinnitu** [comment]
As I understand need something to do with localeFile function like this

```js
var Module = {
    locateFile: function(s) {
      return 'assets/' + s;
    }
  };
```

but where? and how?

**Comment by use-strict** [comment]
See
https://emscripten.org/docs/api_reference/module.html#Module.locateFile
and
https://github.com/use-strict/7z-wasm/blob/master/index.d.ts#L15

e.g.
```ts
import SevenZip from "7z-wasm";

const sevenZip = await SevenZip({
    locateFile: () => { /* ... */ }
});
```

**Comment by vinnitu** [comment]
you are right! thanks

but put 7zz.wasm to public folder and locateFile: (s) => s
