### ISSUE TITLE
Upgrade to latest, non-beta version

### ISSUE THREAD

**Issue by adyster** [use-strict/7z-wasm#6]
How hard would it be to upgrade to latest version? (i.e. the non-beta version)

**Comment by use-strict** [comment]
Assuming they didn't change much from the beta version and the custom patch still applies successfully, it should be a matter of updating the download link in the Dockerfile and testing that everything still works.

**Comment by knowhatamine** [comment]
I would very much appreciate this also. Thanks for your work.
