### ISSUE TITLE
how to open file?

### ISSUE THREAD

**Issue by da0ka** [use-strict/7z-wasm#9]
I can't open file on browser. code is below. why not?

<title>test.htm</title><script type=module>
import SevenZip from "./7zz.es6.js";
const sevenZip=await SevenZip();
sevenZip.FS.readFile("7zz.es6.js");// report No such file or directory
sevenZip.FS.readFile("C:/Users/user/Desktop/7zip7zz.es6.js");// report No such file or directory
</script>

directory
C:/Users/user/Desktop/7zip
┣test.htm
┣7zz.es6.js
┗7zz,wasm.js

**Comment by use-strict** [comment]
See https://emscripten.org/docs/api_reference/Filesystem-API.html

In the browser, you don't have access to the local filesystem. You'd have to upload that file using a standard upload form or drag and drop, then write it to the in-memory file system.

**Comment by lmly9193** [comment]
could you give a example for browser?
Im building a 7z file content previewer,
but i dont understand how to readfile from blobURL.
